name: afar_cabs_user
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  shared_preferences: ^2.0.15
  provider: ^6.0.5
  introduction_screen: ^3.1.1
  get: ^4.6.5
  pinput: ^2.2.21
  image_picker: ^0.8.5+3
  google_sign_in: ^5.4.2
  http: ^0.13.5
  location: ^4.4.0
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  easy_search_bar: ^2.4.2
  form_field_validator: ^1.1.0
  auto_size_text: ^3.0.0
  # otp countdown timer package
  circular_countdown_timer: ^0.2.1
  flutter_countdown_timer: ^4.1.0
  # app version and other details provider
  package_info_plus: ^3.0.2
  # used to search for places
  google_maps_webservice: ^0.0.19
  flutter_google_places: ^0.3.0
  google_api_headers: ^1.5.0+1
  # used to get address from coordinates
  geocoding: ^2.0.5
  # used for outside links
  url_launcher: ^6.1.8
  # used to share text, files etc to other apps
  share_plus: ^6.3.0
  # generating random id's
  uuid: ^3.0.7
  # for showing pop-up message
  blurry: ^1.4.2
  # for showing polylines between start and end points
  flutter_polyline_points: ^1.0.0
  # used for OTP time countdown
  flutter_timer_countdown: ^1.0.5
  simple_timer: ^2.0.0
  neon_circular_timer: ^0.0.7
  # used for picking on map
  google_maps_place_picker_mb: ^3.0.1
  # used for rating
  flutter_rating_bar: ^4.0.1
  # icon border
  icon_decoration: ^1.0.1
  # contact picker
  flutter_native_contact_picker: ^0.0.3
  # it contains some cool predefined widgets
  getwidget: ^3.0.1
  # below package is used for email otp verification
  email_auth: ^1.0.0
  # firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.4
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  # payment integration
  razorpay_flutter: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
#  # launcher icon package
#  flutter_launcher_icons: ^0.11.0

#flutter_icons:
#  android: true
#  ios: true
#  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/onboard/
    - assets/sign_in_up/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
