// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjp3hwr4XQKuOeXLDthmQ_wDXZdRe0QQw',
    appId: '1:300964292041:android:2eb66f7e4748ccf300f418',
    messagingSenderId: '300964292041',
    projectId: 'farcabs',
    storageBucket: 'farcabs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY3mThNbEarpymQ2BRWPJSoL4sjw_lnkg',
    appId: '1:300964292041:ios:b99ea8b61e377ffc00f418',
    messagingSenderId: '300964292041',
    projectId: 'farcabs',
    storageBucket: 'farcabs.appspot.com',
    androidClientId: '300964292041-1cp4t2tvnrmduuosjv427itv29q27n6o.apps.googleusercontent.com',
    iosClientId: '300964292041-30j9r0aqb8vsst0foui1k2vi3r2evkfe.apps.googleusercontent.com',
    iosBundleId: 'com.wings.miles.user.afarCabsUser',
  );
}
